#!/usr/bin/python

import socket, threading, time		# import modulu socket


def postman():
	s = socket.socket()			# vytvoreni objektu soket
	h = socket.gethostname()		# vytvoreni objektu hostname

	host = '192.168.254.100'		# IP adresa, na ktere server nasloucha
	port = 47001				# port, na kterem server nasloucha

	s.connect((host, port))
	s.send(h)

	with open('testfile.recieved', 'wb') as f:
		print 'Zahajuji prenos'
		while True:
#			print('prijimam data...')
			data = s.recv(1024)
#			print('data=%s', (data))
			if not data:
				break
			# write data to a file
			f.write(data)

	f.close()
	print('Prenos dokoncen')
	s.close()
	print('Spojeni uzavreno')

while True:
    time.sleep(10)
    t = threading.Thread(target=postman,args=())
    t.start()
