#!/usr/bin/python

import socket				# import modulu socket

host = "192.168.254.100"		# ip, na ktere se bude naslouchat
port = 47001				# port, na kterem bude naslouchat server

s = socket.socket()			# vytvoreni objektu socket

s.bind((host, port))			# svazat socket s portem
s.listen(5)				# cekani na spojeni od postaka

print 'Server ceka na spojeni....'


while True:
	conn, addr = s.accept()		# navazani spojeni
	print 'Navazano spojeni z ', addr
	data = conn.recv(1024)
	print('Server prijal', repr(data))

	filename='testfile.out'		# cesta k souboru pro odeslani
	f = open(filename,'rb')
	l = f.read(1024)
	while (l):
		conn.send(l)
#		print('Odeslano ',repr(l))
		l = f.read(1024)
	f.close()

	print('Odesialni dokonceno')
	conn.close()
